### ISSUE TITLE
transaction id on request page

### ISSUE THREAD

**Issue by jahshaka** [SenitCorp/bugtracker#111]
there is no transaction created yet then you request funds ?

would be helpful as there should be a id created for every transaction weather sent or requet or completed

as if a user does a request for funds and the other use dont get it then support will need a way to look the transaction up

we had said to remove this - but we should keep it really if we can

**Comment by jayrulez** [comment]
So what is created is a request Id which is not a transaction ID. We can represent this differently for support purposes.
Leaving it as "transaction Id" is misleading so I vote that we remove it.

If we have issues that require us to display the request id in the future then we can add it later.

Let us go with the "Less is More" principle here.

**Comment by jahshaka** [comment]
i beleive that every transaction should have a master Transaction ID that never changes and that is linear in creation. weather the transaction is actioned or not is another thing...

a request for funds should create a new transaction ID but would be parked until actioned... but the transaction ID should not change just the transaction TYPE

EVERY transaction should pull the next available linear transaction ID that can be used to look up any transaction on the system (regardless of the status of the transaction)

weather thats a request for funds, or a mobile topup etc... they should all be linear transaction ID's from the stack A1 A2 A3 etc etc

call me to discuss if need be i am not sure why its not this way right now... any other way will create confusion for support and for transaction management.

if need be the master transaction can be lined to a sub transaction or multiple sub transactions...

and everything recorded for governance... on our private governance blockchain !!!

**Comment by jahshaka** [comment]
so you need the transaction ID for every transaciton to be a meta ID that cna be pulled and should likst everything that makes up the transaciton.... 

transaction A1 is  a send funds

transaction A2 is a mobile topup linked to a send funds to bitrefill

transaction A3 is a request for funds that then creates a request ID etc etc and is either processed or not

transaction A4 is a exchange transaction via app store

transaciton A5 is a shapeshift - linked back to transfer funds into the users wallet

**Comment by jayrulez** [comment]
@SamuelFolkes

**Comment by jayrulez** [comment]
All "real" transaction IDs are linear.
What we see on the activity stream are "Activities".

Activities can be linked to other entities that may be transations (topup, p2p, outgoing send, incoming etc...) or not (kyc update, payment requests, news item etc...).

The transactions are linked to either payment, outgoing, incoming, refill etc... 

Transaction IDs are created for those because they are actual transactions.

Stuff like payment requests, kyc update don't get a transaction ID because they are not "transactions".

What you are referring to as transactions are activities in the system and do have sequential IDs also.

Activities are linked to activity resources which maybe any type of item that you can see in the stream (This includes "transactions" and non-transactions).

If the activity resource is a transaction type then it has a link to the transaction record with the transaction id.

The activity id serves the purpose you described above.

I think this is the proper way to do it and it works well.

However, if you want it to be changed as you described then we can discuss and implement.

**Comment by SamuelFolkes** [comment]
How are we defining transactions here? In the strictest technical sense, a transaction that is not actioned is not actually a transaction, at least not from the perspective of the system. Conflating transaction requests and actual transactions will muddy the distinction between these two distinct entities.

**Comment by jayrulez** [comment]
bump

**Comment by jayrulez** [comment]
bump. We can't close this until we come to a conclusion here...

**Comment by jahshaka** [comment]
then you need a action id differrent from a transaction id or something like that 

everything  should have a action id issued to it when its initiated - that you can use to reference it ?

if a request for funds  is created it shoud have a id to track it in case there is a issue - diffrerent from the transaction id itself as like you said a transaction id is the actual transaction (movement of funds) and should be internal data only really

the action id  ID we need to display for support on tickets and receipts etc... if i pull up a action id it should give  me the transaction id if it was actioned... and if not the activity that created it

support needs a reference number for every action in order to help users - weather its . request for funds, or a kyc reuest - mobile topup - etc

we shoudnt display transaction id really that should be obfuscated

**Comment by jayrulez** [comment]
@jovi959 @Ibar000 please display the activity id for activities in the stream instead of the resource id to close out this issue.

**Comment by Ibar000** [comment]
@jayrulez please explain what you mean by "activity id". I'm not seeing it as a JSON key in the transactions coming from the server.

**Comment by jovi959** [comment]
iOS COmpleted

**Comment by jovi959** [comment]
@Ibar000 this is the first id you see in the object it is called "id"

**Comment by Ibar000** [comment]
android Completed
