### ISSUE TITLE
wallet management and obfuscation

### ISSUE THREAD

**Issue by jahshaka** [SenitCorp/bugtracker#118]
is wallet obfuscation now working ? 

we were to create a new sub-wallet address for the QR code page for users to share and send to receive funds, every time the current one has been used to avoid crating too many... but to have a basic level of obfuscation.

to go with this we need in the app settings a wallets page that lists the adddress of the main wallet as well as all the sub-wallets in a users account, and transactions that went through them... would start with 1 main wallet and 1 sub wallet for all users, then anytime the sub is used we create a new one and increment

reason we need this page is i may shar a address with my  boss to pay me via bitcoin for eg... and give him a sub address which may then oncrement the next time i go there

so we also need a button on the QR code page to get them to the wallet managenet setings page....

robert this was urgent a year ago ???

**Comment by jayrulez** [comment]
This is already implemented.

Whenever the client asks for a wallet address, We check if the last generated address has been used. If is hasn't then we return that otherwise we create a new one and return it.

There is no "main" wallet though. The wallet is a combination of all the addresses for that user.

There is also an api for listing wallet addresses for the user that the client can call to list the addresses on the settings page.

**Comment by jayrulez** [comment]
@Ibar000 @jovi959

**Comment by jayrulez** [comment]
This should be fixed as long as the client behaves as expected. Closing. If you observe something different then please open the issue again
