### ISSUE TITLE
phone still taking me to choose country at registration

### ISSUE THREAD

**Issue by jahshaka** [SenitCorp/bugtracker#120]
so i am on a NEW phone in Madrid - i install mpago and launch the app

i click register

and it takes to to the long list of countries to choose my rass claat country and we are now at 3.0.9

i cancel the choos country crap and my device is set to Spain already as the country

i quit the app and try agian

same thing

takes me to choose my country even though its already defaulting to Spain

so if it is set to fucking Spain why is it asking me to choose my rass claat fucking country man this was to have been fixed ot 3.0.1 already

**Comment by jovi959** [comment]
The country is default to spain on all phones it never actually detected where you were. This happened because the phone couldn't detect your location for whatever reason eg. timeout, spotty net or service not being able to detect location, this is why it prompted you to select a country this feature can be removed if it is an undesirable one.

**Comment by jahshaka** [comment]
yes very undesirable - we cant default to anything but if we need to then lets defualt to london uk english standard please

but .... we need to detect the country

thought we signed up for a new service to help do this via ip address

you can also detect via the phone android  settings ??? my phone is set up as a spanish phone and i was using my home wifi

https://whatismycountry.com/

correctly detects my country as Spain ????? we should be able to as well ???

**Comment by jayrulez** [comment]
closing as this issue is being tracked by issue #147
