### ISSUE TITLE
need country code auto select when singing in

### ISSUE THREAD

**Issue by jahshaka** [SenitCorp/bugtracker#7]
most European countries have the same country code - like spain is 34 and uk is 44

we need to default to the right country code and let the user change it if they need be

currently when you go to log in you hit a monster page of countries to choose fro its not very intuative...

we need to defualt to the main country code and let the user change if the need to - or filter the list that pops up by their country and make the process more intuative...

this means taggin countries with more than 1 area code to help smooth this out and if they ahve more than one code bring up the country lsit with search prefix filled in for their country.

**Comment by jayrulez** [comment]
To have this working properly 1 of the steps will be paying for the ip service.
I recommend this service: https://ipstack.com/product

We can use the basic tier for $10 monthly and upgrade later if we hit any limitations.

**Comment by jayrulez** [comment]
IpStack has implemented and will be available in the next server deployment.

This means that we should always get a country for the IP so that we are not presented with the country list.

The next section part of this issue is to tag countries with multiple area codes and allow users of selected countries to select only from a list of tagged area codes.

I will work with Jovi to get this done.

**Comment by senit** [comment]
I wound use a pop up dialog instead of list if a country has more than one area code ?  And the same list we currently have if they want to change the country of course
